[package]
name = "qwac-trust-anchors"
version = "0.1.0"
edition = "2024"
license = "MPL-2.0"

[dependencies]
base64 = "0.22.1"
chrono = "0.4"
clap = { version = "4.5.48", features = ["derive"] }
reqwest = { version = "0.12.23", features = ["blocking"] }
xml = "1.0.0"
